"""add kindergarten

Revision ID: 08335cd5e88d
Revises: 55dbdb1b22cb
Create Date: 2026-08-07 10:34:59.217026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08335cd5e88d'
down_revision: Union[str, None] = '55dbdb1b22cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children', sa.Column('is_in_kindergarten', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('children', 'is_in_kindergarten')
    # ### end Alembic commands ###
