"""add lifetime stats

Revision ID: 0eacd6190fd7
Revises: 1b2872dc36f5
Create Date: 2026-07-30 16:56:23.236864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eacd6190fd7'
down_revision: Union[str, None] = '1b2872dc36f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lifetime_earned', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('lifetime_work_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lifetime_work_count')
    op.drop_column('users', 'lifetime_earned')
    # ### end Alembic commands ###
