"""add emoji and log_verb to actions

Revision ID: 1a6bccd95f2e
Revises: 47f7d7741ba7
Create Date: 2026-07-14 17:08:49.590644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a6bccd95f2e'
down_revision: Union[str, None] = '47f7d7741ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relationship_actions', sa.Column('emoji', sa.String(length=10), nullable=False))
    op.add_column('relationship_actions', sa.Column('log_verb', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relationship_actions', 'log_verb')
    op.drop_column('relationship_actions', 'emoji')
    # ### end Alembic commands ###
