"""add user chat_id and loan growth tracking

Revision ID: 2f22f975f6fd
Revises: e029de213ede
Create Date: 2026-07-15 12:19:17.466699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f22f975f6fd'
down_revision: Union[str, None] = 'e029de213ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chat_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('loan_last_charge_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'loan_last_charge_at')
    op.drop_column('users', 'chat_id')
    # ### end Alembic commands ###
