"""add daily gigs

Revision ID: 3136dfa3e4e2
Revises: 08335cd5e88d
Create Date: 2026-09-19 07:26:22.606540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3136dfa3e4e2'
down_revision: Union[str, None] = '08335cd5e88d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_gig_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('gig_streak', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gig_streak')
    op.drop_column('users', 'last_gig_completed_at')
    # ### end Alembic commands ###
