"""add cars, family budget, car_id

Revision ID: 32dd8cb4edcb
Revises: 1a6bccd95f2e
Create Date: 2026-07-14 17:54:50.694054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32dd8cb4edcb'
down_revision: Union[str, None] = '1a6bccd95f2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('order')
    )
    op.add_column('relationships', sa.Column('car_id', sa.Integer(), nullable=True))
    op.add_column('relationships', sa.Column('family_budget', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'relationships', 'cars', ['car_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'relationships', type_='foreignkey')
    op.drop_column('relationships', 'family_budget')
    op.drop_column('relationships', 'car_id')
    op.drop_table('cars')
    # ### end Alembic commands ###
