"""add bonus system

Revision ID: 441c60118fef
Revises: 3136dfa3e4e2
Create Date: 2026-09-19 07:48:32.384098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '441c60118fef'
down_revision: Union[str, None] = '3136dfa3e4e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('happy_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('bonus_percent', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_happy_hours_chat_id'), 'happy_hours', ['chat_id'], unique=False)
    op.add_column('users', sa.Column('work_streak_days', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('last_work_streak_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_work_streak_date')
    op.drop_column('users', 'work_streak_days')
    op.drop_index(op.f('ix_happy_hours_chat_id'), table_name='happy_hours')
    op.drop_table('happy_hours')
    # ### end Alembic commands ###
