"""add married_at

Revision ID: 47f7d7741ba7
Revises: 279d4a047f69
Create Date: 2026-07-14 16:49:17.205104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f7d7741ba7'
down_revision: Union[str, None] = '279d4a047f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relationships', sa.Column('married_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relationships', 'married_at')
    # ### end Alembic commands ###
