"""add surprise cooldown

Revision ID: 4acce8d5bc83
Revises: 98fad38cb2d9
Create Date: 2026-07-29 22:28:42.622735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4acce8d5bc83'
down_revision: Union[str, None] = '98fad38cb2d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('surprise_last_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'surprise_last_sent_at')
    # ### end Alembic commands ###
