"""add chat status and updated_at

Revision ID: 55dbdb1b22cb
Revises: d9e227c28665
Create Date: 2026-08-02 12:20:59.971783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55dbdb1b22cb'
down_revision: Union[str, None] = 'd9e227c28665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_chats', sa.Column('member_status', sa.String(length=20), nullable=False, server_default='unknown'))
    op.add_column('bot_chats', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_chats', 'updated_at')
    op.drop_column('bot_chats', 'member_status')
    # ### end Alembic commands ###
