"""add protection and miscarriage

Revision ID: 56c3e3ab4a10
Revises: 72561da7f7dc
Create Date: 2026-07-30 20:08:54.756167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c3e3ab4a10'
down_revision: Union[str, None] = '72561da7f7dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relationships', sa.Column('protection_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('children', sa.Column('will_miscarry', sa.Boolean(), nullable=False, server_default='false'))    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relationships', 'protection_enabled')
    op.drop_column('children', 'will_miscarry')
    # ### end Alembic commands ###
