"""add anniversaries

Revision ID: 5f163fd589ff
Revises: 0eacd6190fd7
Create Date: 2026-07-30 17:22:20.319149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f163fd589ff'
down_revision: Union[str, None] = '0eacd6190fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relationships', sa.Column('last_together_anniversary', sa.Integer(), nullable=True))
    op.add_column('relationships', sa.Column('last_married_anniversary', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relationships', 'last_married_anniversary')
    op.drop_column('relationships', 'last_together_anniversary')
    # ### end Alembic commands ###
