"""add max_pets to houses

Revision ID: 74507d0426d6
Revises: 94e77a506947
Create Date: 2026-09-29 14:39:44.966073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74507d0426d6'
down_revision: Union[str, None] = '94e77a506947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('max_pets', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('houses', 'max_pets')
    # ### end Alembic commands ###
