"""add pet recovery

Revision ID: 94e77a506947
Revises: 441c60118fef
Create Date: 2026-09-27 14:20:31.000278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e77a506947'
down_revision: Union[str, None] = '441c60118fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('is_missing', sa.Boolean(), nullable=False))
    op.add_column('pets', sa.Column('missing_since', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pets', sa.Column('search_method', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'search_method')
    op.drop_column('pets', 'missing_since')
    op.drop_column('pets', 'is_missing')
    # ### end Alembic commands ###
