"""add career progression

Revision ID: 98fad38cb2d9
Revises: 1994512a7ce6
Create Date: 2026-07-29 22:11:28.887049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98fad38cb2d9'
down_revision: Union[str, None] = '1994512a7ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('job_shifts_worked', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'job_shifts_worked')
    # ### end Alembic commands ###
