"""add mood decay and growth tracking

Revision ID: 9eb3ddae4f92
Revises: e98a32128e21
Create Date: 2026-07-15 07:52:31.949987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb3ddae4f92'
down_revision: Union[str, None] = 'e98a32128e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children', sa.Column('last_mood_decay_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('children', 'last_mood_decay_at')
    # ### end Alembic commands ###
