"""add offended state

Revision ID: c913e54a1203
Revises: 56c3e3ab4a10
Create Date: 2026-07-31 12:01:50.367962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c913e54a1203'
down_revision: Union[str, None] = '56c3e3ab4a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relationships', sa.Column('is_offended', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relationships', 'is_offended')
    # ### end Alembic commands ###
