"""add divorce, loans, conception cooldown split

Revision ID: e029de213ede
Revises: 54546859f18f
Create Date: 2026-07-15 11:13:40.731869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e029de213ede'
down_revision: Union[str, None] = '9eb3ddae4f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relationships', sa.Column('last_conception_was_success', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('loan_amount', sa.Integer(), nullable=False, server_default='0'))    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'loan_amount')
    op.drop_column('relationships', 'last_conception_was_success')
    # ### end Alembic commands ###
