"""add pregnancy, birth, chat_id

Revision ID: e87ee81b8e8f
Revises: f3ebc353f4df
Create Date: 2026-07-14 22:15:53.919724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e87ee81b8e8f'
down_revision: Union[str, None] = 'f3ebc353f4df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children', sa.Column('status', sa.Enum('PREGNANT', 'ALIVE', name='child_status'), nullable=False))
    op.add_column('children', sa.Column('traits', sa.String(length=200), nullable=True))
    op.add_column('children', sa.Column('mood', sa.Integer(), nullable=False))
    op.add_column('children', sa.Column('age_stage', sa.Enum('BABY', 'TODDLER', 'CHILD', 'TEEN', name='age_stage'), nullable=False))
    op.add_column('children', sa.Column('conceived_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('children', sa.Column('due_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('children', sa.Column('born_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('children', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('children', 'gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', name='gender'),
               nullable=True)
    op.drop_column('children', 'birth_date')
    op.drop_column('children', 'growth_stage')
    op.add_column('relationships', sa.Column('chat_id', sa.BigInteger(), nullable=True))
    op.add_column('relationships', sa.Column('last_conception_attempt_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relationships', 'last_conception_attempt_at')
    op.drop_column('relationships', 'chat_id')
    op.add_column('children', sa.Column('growth_stage', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('children', sa.Column('birth_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False))
    op.alter_column('children', 'gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', name='gender'),
               nullable=False)
    op.alter_column('children', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('children', 'born_at')
    op.drop_column('children', 'due_at')
    op.drop_column('children', 'conceived_at')
    op.drop_column('children', 'age_stage')
    op.drop_column('children', 'mood')
    op.drop_column('children', 'traits')
    op.drop_column('children', 'status')
    # ### end Alembic commands ###
