"""add child actions

Revision ID: e98a32128e21
Revises: e87ee81b8e8f
Create Date: 2026-07-14 23:50:42.550163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e98a32128e21'
down_revision: Union[str, None] = 'e87ee81b8e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('stage', sa.Enum('BABY', 'TODDLER', 'CHILD', 'TEEN', name='child_action_stage'), nullable=False),
    sa.Column('affection_reward', sa.Integer(), nullable=False),
    sa.Column('mood_reward', sa.Integer(), nullable=False),
    sa.Column('bonus_trait', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.add_column('children', sa.Column('last_interaction_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('children', 'last_interaction_at')
    op.drop_table('child_actions')
    # ### end Alembic commands ###
