"""add casino_last_bet_at

Revision ID: f3ebc353f4df
Revises: 32dd8cb4edcb
Create Date: 2026-07-14 20:14:33.087444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ebc353f4df'
down_revision: Union[str, None] = '32dd8cb4edcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('casino_last_bet_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'casino_last_bet_at')
    # ### end Alembic commands ###
